# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  go: circleci/go@1.7.3

jobs:
  build_and_test: # this can be any name you choose
    executor:
      name: go/default # Use the default executor from the orb
      tag: '1.12' # Specify a version tag
    steps:
      - checkout # checkout source code
      - go/load-cache # Load cached Go modules.
      #- go/mod-download # Run 'go mod download'.
      - go/save-cache # Save Go modules to cache.
      - run:
          name: "build" 
          command: |
            export CGO_ENABLED
            CGO_ENABLED=0
            export GOOS
            mkdir artifacts
            for T in linux darwin; do
              mkdir -p release/"$T"
              GOOS=$T
              go build -a -installsuffix cgo -o release/"$T"/kube-compose .
              (
                cd release/"$T"
                tar -zcvf kube-compose.tar.gz kube-compose
                mv kube-compose ../../artifacts/kube-compose."$T"
                mv kube-compose.tar.gz ../../artifacts/kube-compose."$T".tar.gz
              )
            done
            ls -la artifacts/
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=0.0.1
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA 1} -delete ${VERSION} ./artifacts/ 
      - run:
          name: "golangci-lint"
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh |
  sh -s -- -b "$(go env GOPATH)"/bin v1.16.0 || true 
      # go get github.com/mattn/goveralls 
      - go/test: # Runs 'go test ./...' but includes extensive parameterization for finer tuning.
          covermode: atomic
          failfast: true
          race: true



# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  go-with-the-flow:
    jobs:
      - build_and_test
